/**
 * POST /api/system/install-safe-updates
 *
 * Install only SAFE (patch-level) dependency updates.
 *
 * Improvement 4: After successful installs, automatically commit
 * package.json and package-lock.json so the repo stays in sync.
 * The commit message lists every updated package for traceability.
 * Git commit is best-effort — if git is not available or the working
 * tree is dirty, the install still succeeds and committed: false is returned.
 *
 * Requires: authenticated user session.
 *
 * Body: { packageNames?: string[] }
 *
 * SAFETY RULES:
 *   - Only packages with updateType === 'patch' are ever installed.
 *   - Never installs major or minor updates.
 *   - Disabled in production unless ALLOW_RUNTIME_INSTALLS=true.
 */

import { NextResponse } from 'next/server';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { requireApiUser } from '@/lib/auth/require-auth';
import {
  runDependencyAudit,
  getSafeUpdateCandidates,
} from '@/lib/services/dependency-audit.service';
import { captureException, captureMessage } from '@/lib/observability/sentry';
import { parseJsonBody } from '@/lib/api/errors';
import { invalidateCache } from '@/lib/redis';

const execAsync = promisify(exec);
export const dynamic = 'force-dynamic';
export const maxDuration = 120;

interface InstallBody {
  packageNames?: string[];
}

async function gitCommitUpdates(
  updated: Array<{ name: string; from: string; to: string }>,
): Promise<{ committed: boolean; commitHash?: string; reason?: string }> {
  try {
    const { stdout: version } = await execAsync('git --version', { timeout: 5_000 });
    if (!version) return { committed: false, reason: 'git not available' };

    await execAsync('git add package.json package-lock.json', {
      cwd: process.cwd(), timeout: 10_000,
    });

    const datePart = new Date().toISOString().split('T')[0];
    const pkgList = updated.map(u => `  - ${u.name}: ${u.from} → ${u.to}`).join('\n');
    const commitMsg = [
      `chore(deps): install ${updated.length} safe patch update(s) [${datePart}]`,
      '',
      'Updated packages:',
      pkgList,
      '',
      'Generated by AutoMint Dependency Update Center',
    ].join('\n');

    await execAsync(`git commit -m ${JSON.stringify(commitMsg)}`, {
      cwd: process.cwd(), timeout: 15_000,
    });

    const { stdout: hash } = await execAsync('git rev-parse --short HEAD', {
      cwd: process.cwd(), timeout: 5_000,
    });

    return { committed: true, commitHash: hash.trim() };
  } catch (err) {
    // git not available, working tree dirty, or no staged changes — non-fatal
    return { committed: false, reason: err instanceof Error ? err.message : String(err) };
  }
}

export async function POST(request: Request) {
  const auth = await requireApiUser();
  if ('error' in auth) return auth.error;

  if (process.env.NODE_ENV === 'production' && process.env.ALLOW_RUNTIME_INSTALLS !== 'true') {
    return NextResponse.json(
      {
        error:
          'Runtime package installation is disabled in production. ' +
          'Set ALLOW_RUNTIME_INSTALLS=true to enable (CI/development environments only).',
      },
      { status: 403 },
    );
  }

  const body = await parseJsonBody<InstallBody>(request).catch(() => ({}) as InstallBody);
  const requestedPackages = body.packageNames;

  try {
    const report = await runDependencyAudit({ devPackages: true });
    let candidates = getSafeUpdateCandidates(report);

    if (requestedPackages && requestedPackages.length > 0) {
      const requested = new Set(requestedPackages);
      candidates = candidates.filter((p) => requested.has(p.name));
    }

    if (candidates.length === 0) {
      return NextResponse.json({
        ok: true,
        updated: [],
        skipped: [{ name: '*', reason: 'No safe patch updates available' }],
        failed: [],
        committed: false,
      });
    }

    const updated: Array<{ name: string; from: string; to: string }> = [];
    const skipped: Array<{ name: string; reason: string }> = [];
    const failed: Array<{ name: string; error: string }> = [];

    for (const pkg of candidates) {
      if (pkg.classification !== 'SAFE' || pkg.updateType !== 'patch') {
        skipped.push({
          name: pkg.name,
          reason: `Skipped: ${pkg.classification} update (${pkg.updateType}). Only patch updates are installed.`,
        });
        continue;
      }

      try {
        const flag = pkg.isDev ? '--save-dev' : '--save';
        await execAsync(`npm install ${flag} ${pkg.name}@${pkg.latestVersion}`, {
          cwd: process.cwd(), timeout: 30_000,
        });
        updated.push({ name: pkg.name, from: pkg.currentVersion, to: pkg.latestVersion });
        await captureMessage('Safe package update installed', {
          area: 'dependency-audit',
          level: 'info',
          context: { userId: auth.userId, package: pkg.name, from: pkg.currentVersion, to: pkg.latestVersion },
          fingerprint: ['dependency-audit', 'install'],
        });
      } catch (err) {
        failed.push({ name: pkg.name, error: err instanceof Error ? err.message : String(err) });
        await captureException(err, {
          area: 'dependency-audit',
          context: { userId: auth.userId, package: pkg.name },
          fingerprint: ['dependency-audit', 'install-failed'],
        });
      }
    }

    // Improvement 4: commit the lockfile changes to git
    let gitResult: { committed: boolean; commitHash?: string; reason?: string } = { committed: false };
    if (updated.length > 0) {
      gitResult = await gitCommitUpdates(updated);
    }

    // Invalidate the report cache so the next scan reflects the new versions
    try {
      await invalidateCache('dep-report:all');
      await invalidateCache('dep-report:prod');
    } catch { /* non-fatal */ }

    return NextResponse.json({
      ok: true, updated, skipped, failed,
      committed: gitResult.committed,
      commitHash: gitResult.commitHash,
      commitSkipReason: gitResult.reason,
    });
  } catch (error) {
    await captureException(error, {
      area: 'dependency-audit',
      context: { userId: auth.userId },
      fingerprint: ['dependency-audit', 'install-safe-updates'],
    });
    const message = error instanceof Error ? error.message : 'Install failed';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
